-- 코드를 입력하세요
SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    CAST(
        (
            C.DAILY_FEE * 30
            * (1 - COALESCE(DP.DISCOUNT_RATE, 0) / 100.0)
        ) AS SIGNED
    ) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON C.CAR_TYPE = DP.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN 
(
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01' OR START_DATE <= 2022-11-30
)
AND (
    C.DAILY_FEE * 30 * (1 - COALESCE(DP.DISCOUNT_RATE, 0) / 100.0)
) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
