-- 코드를 입력하세요
SELECT 
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    COUNT(DISTINCT os.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT os.USER_ID) / total_users.total_cnt, 1) AS PUCHASED_RATIO
FROM USER_INFO ui
JOIN ONLINE_SALE os ON ui.USER_ID = os.USER_ID
JOIN (
    SELECT COUNT(*) AS total_cnt
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
) AS total_users
WHERE ui.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE)
ORDER BY YEAR, MONTH;