-- 코드를 입력하세요
SELECT fd.PRODUCT_ID, fd.PRODUCT_NAME, SUM(fo.amount * fd.price) AS TOTAL_SALES
FROM FOOD_PRODUCT fd join FOOD_ORDER fo on fd.PRODUCT_ID = fo.PRODUCT_ID
WHERE fo.PRODUCE_DATE >= '2022-05-01' and fo.PRODUCE_DATE <= '2022-05-31'
GROUP BY fd.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, fd.PRODUCT_ID ASC;